In [2]:
import numpy as np 

Arithmetic Operations

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr1
arr2

array([ 6,  7,  8,  9, 10])

In [5]:
arr_sum = arr1 + arr2
arr_sum 

array([ 7,  9, 11, 13, 15])

In [6]:
arr_sub  = arr1 - arr2
arr_sub

array([-5, -5, -5, -5, -5])

In [7]:
arr_mul = arr1 * arr2
arr_mul

array([ 6, 14, 24, 36, 50])

In [8]:
arr_mod = arr1 % arr2
arr_mod

array([1, 2, 3, 4, 5])

In [9]:
arr_div = arr1 / arr2
arr_div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Broadcasting

In [10]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [11]:
arr + 10 

array([11, 12, 13, 14, 15])

In [12]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow Copy 

In [14]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [23]:
a
b = a 

In [27]:
b[0] = 99
b

array([  99,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
       1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

Matrix Operation 

In [29]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [30]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
A @ B

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [33]:
np.dot(A,B)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [34]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])