In [2]:
import numpy as np

Basic Array Creation 

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

2 Dimensional Matrix 

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function 

In [11]:
arr = np.arange(1,11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr =np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Generation function

In [17]:
np.random.rand(3)

array([0.30903614, 0.77050514, 0.99103172])

In [34]:
np.random.randn(3)

array([0.17530081, 1.77486911, 1.08534742])

In [36]:
np.random.randint(10,100,100)

array([18, 10, 35, 58, 76, 86, 64, 86, 71, 81, 37, 56, 46, 30, 53, 76, 69,
       50, 90, 64, 67, 50, 79, 78, 57, 55, 63, 57, 81, 80, 55, 44, 92, 52,
       34, 59, 75, 58, 84, 76, 12, 49, 52, 89, 57, 82, 89, 20, 57, 27, 76,
       90, 52, 99, 31, 51, 35, 82, 36, 69, 33, 17, 73, 53, 80, 80, 36, 27,
       21, 66, 52, 39, 44, 50, 27, 90, 57, 24, 37, 62, 78, 20, 44, 18, 59,
       46, 18, 11, 75, 98, 38, 84, 14, 35, 15, 73, 90, 27, 91, 37])

Array Attributes

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [41]:
arr.size

9

In [42]:
arr.dtype

dtype('int32')

Array Methods 

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr.min()

1

In [45]:
arr.max()

9

In [46]:
arr.sum()

45

In [47]:
np.sum(arr,axis=0) #column wise sum

array([12, 15, 18])

In [48]:
arr.std()

2.581988897471611

In [49]:
arr.argmax()

8

In [50]:
arr.argmin()

0

In [51]:
arr.mean()

5.0

Reshaping and Resizing 