In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

20

In [6]:
arr_slice = arr[1:4:2]

In [7]:
arr_slice

array([12, 14])

NUMPY INDEXING AND SLICING OF MATRIX 

In [8]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [11]:
arr[4,4]

29

In [14]:
arr[2:5,4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [15]:
arr[2:]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

BOOLEAN INDEXING 

In [16]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
boolean_arr = arr % 2 == 0
boolean_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [18]:
arr = arr[boolean_arr]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])