In [4]:
import numpy as np

Valid Suduku

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [12]:
b = np.sum(s , axis=1)
for i in b:
    if i != 45 :
        print("This is not a valid sudoku")
        break
else:
    print("This is a valid sudoku for rows")

This is a valid sudoku for rows


In [13]:
c = np.sum (s , axis=0)
for i in c:
    if i != 45 :
        print("This is not a valid sudoku")
        break
else:
    print("This is a valid sudoku for columns")

This is a valid sudoku for columns


In [6]:
#explanation : in sudoku , each row and column should have numbers from 1 to 9 without repetition. So the sum of each row and column should be 45 (1+2+3+4+5+6+7+8+9 = 45). If any row or column does not sum up to 45, then it is not a valid sudoku.
for i in range(0 , 9 , 3):
    for j in range (0 , 9 , 3):
        n = s [i:i+3 , j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Question

In [9]:
import numpy as np 
#columns : [age , math marks , science marks]

data = np.array([
    [18, 85 ,78], #student 1
    [19, 92 ,88], #student 2
    [17, 76 ,95], #student 3
    [18, 65 ,70], #student 4
    [20, 90 ,85]  #student 5
])

In [10]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [12]:
#Find the average age of the students.
average_age = data[:,0].mean()
print("Average age of the students is : " , average_age)

Average age of the students is :  18.4


In [13]:
#Extract the math marks of all students.

math_marks = data[: , 1]
print("Math marks of all students are : " , math_marks)

Math marks of all students are :  [85 92 76 65 90]


In [14]:
#find the highest science marks among all students.
highest_science_marks = data[:,2].max()
print("Highest science marks among all students is : " , highest_science_marks)

Highest science marks among all students is :  95


In [15]:
#Get Details of students who scored more than 90 in math.

students_scored_more_than_90_in_math = data[data[:,1] > 90]
print("Details of students who scored more than 90 in math are : " , students_scored_more_than_90_in_math)

Details of students who scored more than 90 in math are :  [[19 92 88]]


In [16]:
#increase the math marks of all students by 5.

data[:,1] = data[: , 1] + 5
print("Math marks of all students after increasing by 5 are : " , data[:,1])

Math marks of all students after increasing by 5 are :  [90 97 81 70 95]


In [19]:
#find how many students are below 19 years of age.

students_below_19_years_of_age = data[data[:,0] < 19]
count_below_19 = len(students_below_19_years_of_age)
print("Number of students below 19 years of age: ", count_below_19)
print("Details of students who are below 19 years of age are : " , students_below_19_years_of_age)

Number of students below 19 years of age:  3
Details of students who are below 19 years of age are :  [[18 90 78]
 [17 81 95]
 [18 70 70]]


In [20]:
#calculate the average marks in each subject.(column wise average)
average_math_marks = data[:,1].mean()
average_science_marks = data[:,2].mean()    
print("Average math marks of all students is : " , average_math_marks)
print("Average science marks of all students is : " , average_science_marks)

Average math marks of all students is :  86.6
Average science marks of all students is :  83.2


In [21]:
#get data of scored atleast 80 in both subjects.
student_who_scored_80_in_both_subjects = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
print("Details of students who scored atleast 80 in both subjects are : " , student_who_scored_80_in_both_subjects)

Details of students who scored atleast 80 in both subjects are :  [[19 97 88]
 [17 81 95]
 [20 95 85]]


In [22]:
#replace the science marks to 0 for student who scored less than 75 in science
data[data[:,2] < 75 , 2] = 0
print("Data after replacing science marks to 0 for students who scored less than 75 in science : " , data)

Data after replacing science marks to 0 for students who scored less than 75 in science :  [[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
